### ISSUE TITLE
What is this and what to do?

### ISSUE THREAD

**Issue by Quincy-seun** [NIXBLACK11/LayerZero#1]
Your readme file not clear enough. Is this a way to interact with Layerzero and how to go about it?

**Comment by NIXBLACK11** [comment]
This is about a tutorial I am following to bridge a mock OFT from Solana to Sepoila and vice-versa.
If you want to do something similar check out their official tutorial.
[OFT-Solana](https://github.com/LayerZero-Labs/devtools/tree/main/examples/oft-solana)
